# Config file template

project:
  platform: github/gitlab
  owner: org-name
  repo: repo-name

repo-info:
  ci-cd-path: path/to/ci-cd/config        # e.g. .travis.yaml, Jenkinsfile, .github/workflows, .gitlab-ci.yaml
  protected-branches:
    - master
    - develop
    - other-branch

policies:
  - control: c1
    enabled: true/false
    path: "<path to policies>/auth.rego"
  - control: c2
    enabled: true/false
    path: "<path to policies>/signed-commits.rego"
  - control: c3
    enabled: true/false
    path: "<path to policies>/auth-key-expiry.rego"
  - control: c4
    enabled: true/false
    path: "<path to policies>/auth-key-read-only.rego"


slack:
  enabled: true/false
  notification-channel: "<channel-name>"