# Config file template

project:
  platform: github/gitlab
  owner: org-name
  repo: repo-name

repo-info-checks:
  trusted-data-file: path/to/trusted-data.json
  ci-cd-path: path/to/ci-cd/config        # e.g. .travis.yaml, Jenkinsfile, .github/workflows, .gitlab-ci.yaml
  protected-branches:
    - master
    - develop
    - other-branch
