# Config file for test

project:
  platform: github
  owner: oc
  repo: my-app-repo

repo-info-checks:
  ci-cd-path: .github/workflows
  policies:
    - control: c1
      enabled: true
      path: "<path to policies>/auth.rego"
    - control: c2
      enabled: true
      path: "<path to policies>/signed-commits.rego"
    - control: c3
      enabled: true
      path: "<path to policies>/auth-key-expiry.rego"
    - control: c4
      enabled: true
      path: "<path to policies>/auth-key-read-only.rego"
  protected-branches:
    - master
    - develop

notifications:
  slack:
    enabled: true
    level: INFO
    notification-channel: secure-pipeline