# Config file for test

project:
  platform: github
  owner: oc
  repo: my-app-repo

repo-info-checks:
  trusted-data-file: oc-trusted-config.json
  ci-cd-path: .github/workflows
  protected-branches:
    - master
    - develop
