name: "Continuous Integration"
on: [push]
jobs:
  lint:
    name: "Lint"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Lint"
        uses: golangci/golangci-lint-action@v2
      - name: "Format"
        uses: Jerome1337/gofmt-action@v1.0.4
        with:
          gofmt-flags: '-l -d'
  test:
    name: "App Build and Test"
    runs-on: ubuntu-latest
    steps:
      - name: "Check out source code"
        uses: actions/checkout@v1
      - name: "Set up Go 1.16"
        uses: actions/setup-go@v1
        with:
          go-version: 1.16
      - name: "Build"
        env:
          GOPROXY: "https://proxy.golang.org"
        run: go build .
      - name: "Test"
        env:
          GOPROXY: "https://proxy.golang.org"
        run: make test
  opa-test:
    name: "Policies Test"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
      - name: "Download OPA Binary"
        run: |
          curl -L -o opa https://openpolicyagent.org/downloads/latest/opa_linux_amd64
          chmod 755 ./opa
      - name: "Test"
        run: |
          ./opa test app/policies/github/*.rego -v
          ./opa test app/policies/gitlab/*.rego -v